---
version: 2
executorType: docker
containerInfo:
  - image: dickeyxxx/cli-engine@sha256:090e7e327787303491f27482f021b9fbcfeac1d379a20769c7524c1c53b68c88
stages:
  build:
    workDir: ~/cli
    steps:
      - type: checkout
      - type: cache-restore
        key: cli
      - type: shell
        command: |
          set -exu
          yarn
          ./bin/run version
          ./bin/run help
      - type: cache-save
        key: cli
        paths:
          - /usr/local/share/.cache/yarn
      - type: deploy
        shell: /bin/bash
        command: |
          set -exu
          TAG=`git describe --exact-match HEAD || echo NOTAG`
          if [ "${TAG}" != "NOTAG" ]; then
            yarn run release beta
          fi
          if [ "${CIRCLE_BRANCH}" == "v6" ]; then
            yarn run release v6
          fi
          if [ "${CIRCLE_BRANCH}" == "v6-philipe" ]; then
            yarn run release v6-philipe
          fi
